In [7]:
import numpy as np

In [8]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [9]:
m = [v, v, v]  #matrix of numbers

In [10]:
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [11]:
v[0] = "python"

In [12]:
m

[['python', 0.75, 1.0, 1.5, 2.0],
 ['python', 0.75, 1.0, 1.5, 2.0],
 ['python', 0.75, 1.0, 1.5, 2.0]]

In [13]:
#use deepcopy to avoid this issue
from copy import deepcopy

In [14]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [15]:
m = 3 * [deepcopy(v),]

In [16]:
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [17]:
v[0] = "python"

In [18]:
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [19]:
a = np.array([0.5, 0.75, 1.0, 1.5, 2.0])

In [20]:
type(a)

numpy.ndarray

In [21]:
a.sum()  #sum of all elements

5.75

In [22]:
a.std()  #standard deviation

0.53851648071345037

In [23]:
a.cumsum()  #running cumulative sum

array([ 0.5 ,  1.25,  2.25,  3.75,  5.75])

In [24]:
a * 2

array([ 1. ,  1.5,  2. ,  3. ,  4. ])

In [25]:
np.sqrt(a)

array([ 0.70710678,  0.8660254 ,  1.        ,  1.22474487,  1.41421356])

In [26]:
b = np.array([a, a*2])

In [27]:
b[0]

array([ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ])

In [28]:
b[0, 2], b[0][2]

(1.0, 1.0)

In [29]:
b.sum()

17.25

In [30]:
b

array([[ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ]])

In [31]:
b.sum(axis=0)

array([ 1.5 ,  2.25,  3.  ,  4.5 ,  6.  ])

In [32]:
b.sum(axis=1)

array([  5.75,  11.5 ])

In [33]:
c = np.zeros((2,3,4), dtype="i", order='C')

In [34]:
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [38]:
d = np.ones_like(c, dtype='f8', order='C')

In [39]:
d

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [40]:
import random

In [41]:
I = 5000

In [42]:
%time mat = [[random.gauss(0, 1) for j in range(I)] for i in range(I)]

Wall time: 16.5 s


In [43]:
%time mat = np.random.standard_normal((I, I))

Wall time: 696 ms


In [44]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/pets', 'i4', 2)])

In [46]:
e = np.array([('Smith', 45, 1.93423, [0, 1]), ('John', 53, 1.72, [2, 2])], dtype=dt)

In [47]:
e

array([(b'Smith', 45,  1.93422997, [0, 1]),
       (b'John', 53,  1.72000003, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/pets', '<i4', (2,))])

In [49]:
e["Name"]

array([b'Smith', b'John'],
      dtype='|S10')

In [50]:
e[1]['Age']

53

In [51]:
r = np.random.standard_normal((4, 3))

In [52]:
t = np.random.standard_normal((4, 3))

In [53]:
r+t

array([[-1.97118155, -0.9358466 , -4.47441226],
       [ 1.44630824, -0.42719301, -0.38577545],
       [-1.8518981 ,  0.12770547,  0.18701429],
       [ 1.53971639, -0.96582538, -0.71049421]])

In [54]:
r

array([[-0.91069019, -0.95960669, -2.46655141],
       [ 0.35887506, -0.04377909, -1.59231956],
       [-0.28040065,  2.32746187,  0.41051604],
       [ 0.96437853,  0.00773119,  0.83016563]])

In [55]:
s = np.random.standard_normal(3)

In [56]:
s

array([ 0.18095061, -0.99084477, -0.03380471])

In [57]:
r+s

array([[-0.72973958, -1.95045146, -2.50035612],
       [ 0.53982567, -1.03462386, -1.62612427],
       [-0.09945004,  1.3366171 ,  0.37671132],
       [ 1.14532914, -0.98311358,  0.79636092]])

In [58]:
s = np.random.standard_normal(4)

In [59]:
r+s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [60]:
r.transpose() + s

array([[-1.04431362,  0.11923067,  1.52239893,  1.04358784],
       [-1.09323012, -0.28342348,  4.13026145,  0.0869405 ],
       [-2.60017484, -1.83196395,  2.21331562,  0.90937494]])

In [61]:
import math

In [62]:
math.sin(r)

TypeError: only length-1 arrays can be converted to Python scalars

In [63]:
np.sin(r)

array([[-0.78992715, -0.81896594, -0.62492951],
       [ 0.35122118, -0.04376511, -0.99976838],
       [-0.27674067,  0.72712916,  0.39908254],
       [ 0.82169488,  0.00773111,  0.73804314]])

In [64]:
##############memory#################

In [65]:
x = np.random.standard_normal((5, 10000000))

In [66]:
y = 2 * x + 3

In [67]:
C = np.array((x, y), order="C")

In [68]:
F = np.array((x, y), order="F")

In [69]:
C[:2].round(2)

array([[[-0.36, -1.71, -0.63, ...,  1.32,  1.32, -0.67],
        [ 1.78, -0.43, -0.36, ...,  0.15, -1.69,  1.13],
        [-0.07, -0.11,  0.36, ...,  1.03,  0.26, -2.07],
        [ 0.15, -1.44,  1.73, ...,  0.75, -0.47,  0.38],
        [-0.81,  0.34, -0.45, ..., -0.26,  1.57, -0.12]],

       [[ 2.27, -0.41,  1.74, ...,  5.64,  5.64,  1.67],
        [ 6.56,  2.14,  2.28, ...,  3.29, -0.39,  5.27],
        [ 2.87,  2.78,  3.72, ...,  5.05,  3.51, -1.15],
        [ 3.29,  0.12,  6.45, ...,  4.5 ,  2.06,  3.76],
        [ 1.38,  3.68,  2.1 , ...,  2.49,  6.15,  2.76]]])

In [70]:
%timeit C.sum()

119 ms ± 3.85 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [71]:
%timeit F.sum()

119 ms ± 9.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [72]:
%timeit C.sum(axis=0)

273 ms ± 14.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [73]:
%timeit F.sum(axis=0)

971 ms ± 49.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
%timeit C.sum(axis=1)

171 ms ± 3.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [75]:
%timeit F.sum(axis=1)

2.04 s ± 59.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
